### ISSUE TITLE
advice on pre-processing

### ISSUE THREAD

**Issue by cstrlln** [kevinrue/velociraptor#35]
Hello,
I know is not the purpose of your tool but in the past had a lot of trouble making velocity packages work and always came back to issues with the pre-processing to get the spliced and unspliced matrices.
I really would like to try velociraptor as I do my analysis basically only on R and using SCE objects.
Do you have a suggestion for a preprocessing pipeline that will work with scvelo/velociraptor?

Thanks for any feedback on this, or any tip on a starting point.

**Comment by csoneson** [comment]
You could check out this tutorial, which shows how to prepare the reference and run the quantification using `alevin`: https://combine-lab.github.io/alevin-tutorial/2020/alevin-velocity/ (assuming that you have 10x data or similar - for full-length protocols the reference generation would be the same but you'd use `Salmon` directly for the quantification).

**Comment by cstrlln** [comment]
Thank you!

Would like get your advice on one more thing: let's say I already did all my analysis based on an exonic count matrix from 'cellranger count' output. Can I just use the results of the velocity from the spliced counts and embed on my exonic analysis or is better to redo analysis fully on the spliced counts instead of cellranger output?

**Comment by csoneson** [comment]
Yeah, that's a good question - there's a bit of discussion [here](https://github.com/kevinrue/velociraptor/blob/8ec54c1731a1acda51e7040215afaafcd2547815/vignettes/userguide.Rmd#L66-L70) and [here](https://github.com/kevinrue/velociraptor/blob/8ec54c1731a1acda51e7040215afaafcd2547815/R/scvelo.R#L66-L78). Rather than the use of 'exonic' or 'spliced' matrices though, I would guess that the major cause for discrepancies would be related to the different tools (e.g., CellRanger vs alevin).

**Comment by cstrlln** [comment]
Cool thanks, this was very helpful!
