### ISSUE TITLE
is there a function to identify important genes in velociraptor? 

### ISSUE THREAD

**Issue by zh-zhang1984** [kevinrue/velociraptor#51]
the original python `scvelo` provide functions to identify important genes as follows, but I cannot find one in the _velociraptor_ package. 
### Identify important genes

> We need a systematic way to identify genes that may help explain the resulting vector field and inferred lineages. To do so, we can test which genes have cluster-specific differential velocity expression, being siginificantly higher/lower compared to the remaining population. The module scv.tl.rank_velocity_genes runs a differential velocity t-test and output a gene ranking for each cluster. Thresholds can be set (e.g. min_corr) to restrict the test on a selection of gene candidates.

**Comment by kevinrue** [comment]
Hello,

Since `velociraptor` converts the AnnData object to a SingleCellExperiment, implementing this functionality would require to convert the object back to `AnnData` (hoping that we haven't lost critical information in the process). I'm not sure that is possible, and I'm too short on time right now to look into it.

At present, `velociraptor` is focused on running the `scvelo` method itself. If you aim to write a workflow that combine multiple functions of scvelo, it sounds like it would be worth spending some of your time using directly the scvelo Python package, so that it is all immediately compatible.

Best
Kevin

**Comment by zh-zhang1984** [comment]
Thank you for your informtion
