### ISSUE TITLE
path to update matplotlib

### ISSUE THREAD

**Issue by YOU-k** [kevinrue/velociraptor#55]
Hi who's concerning, I was trying to run scvelo, but I came across a problem here:
```
Error in py_module_import(module, convert = convert) : 
  AttributeError: module 'matplotlib' has no attribute 'get_data_path'
```
I checked my python configs.
```
py_config()
python:         /stornext/Home/data/allstaff/y/you.y/.cache/R/basilisk/1.6.0/velociraptor/1.4.0/env/bin/python
libpython:      /stornext/Home/data/allstaff/y/you.y/.cache/R/basilisk/1.6.0/velociraptor/1.4.0/env/lib/libpython3.7m.so
pythonhome:     /stornext/Home/data/allstaff/y/you.y/.cache/R/basilisk/1.6.0/velociraptor/1.4.0/env:/stornext/Home/data/allstaff/y/you.y/.cache/R/basilisk/1.6.0/velociraptor/1.4.0/env
version:        3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
numpy:          /stornext/Home/data/allstaff/y/you.y/.cache/R/basilisk/1.6.0/velociraptor/1.4.0/env/lib/python3.7/site-packages/numpy
numpy_version:  1.19.1

NOTE: Python version was forced by use_python function
```

And the I tried to use 
```
py_install()
conda_install() 
```
both to update the matplotlib. However, they both think the package should no longer to updated. 

Is there any suggestion for me to set the right path and update that module? Also, will updating the module fix the error I faced?
Thanks a lot!
Cheers,
Chloe

**Comment by YOU-k** [comment]
It was fixed without any updating of packages. Thanks anyway.

**Comment by kevinrue** [comment]
Apologies for the slow reply.

I'm glad to hear that the situation resolved itself.

Your original message lacks the command(s) that you ran to run into the issue.

The only thing I can see that piqued my attention is the `NOTE: Python version was forced by use_python function`. I can't see that functions used anywhere in velociraptor, basilisk, and basilisk.utils, so I wonder whether you might have somehow altered the Python configuration in your first session where the error happened, and maybe your second session instead had the right configuration (I can't say since your latest message doesn't provide the equivalent information). Those things are really hard to track and diagnose without sharing your complete session information with us.

In any case, thanks for reporting the issue. I'm going to close it since it is fixed for you , but feel free to post additional information here that might help others who run into the same issue in the future, as they might come across this issue when they search online for a fix.

**Comment by YOU-k** [comment]
Thanks anyway! 👍
